name: devide_manager
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.0.0+3
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  clippy_flutter: ^2.0.0-nullsafety.1
  uuid: ^3.0.7
  image_picker: ^0.8.7+2
  image_network: ^2.5.2
  flutter_spinkit: ^5.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.11
  flutter_inappwebview: ^5.7.2+3
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.1
  express_dt: ^1.0.5
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.6
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Logo_Khoa/
    - assets/Images_TOD/
    - assets/Gif_Status/
    - assets/Icon/
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
